from __future__ import annotations

from typing import Any


WORKFLOWS: dict[str, list[dict[str, Any]]] = {
    "WF-1_PROJECT_INTAKE": [
        {"prompt_id": "P-SECURITY-CLASSIFY"},
        {"prompt_id": "P-SECURITY-CLASSIFY-CRITIC"},
        {"prompt_id": "P-SCHEME-EXTRACT"},
        {"prompt_id": "P-SCHEME-CRITIC"},
        {"prompt_id": "P-PROJECT-DEFINITION-EXTRACT"},
        {"prompt_id": "P-PROJECT-DEFINITION-CRITIC"},
        {"prompt_id": "P-FACT-EXTRACT"},
        {"prompt_id": "P-FACT-CRITIC"},
        {"prompt_id": "P-PROJECT-READINESS-CRITIC"},
    ],
    "WF-2_TEMPLATE_EXTRACTION": [
        {"prompt_id": "P-TEMPLATE-EXTRACT"},
        {"prompt_id": "P-TEMPLATE-CRITIC"},
    ],
    "WF-3_HYBRID_ONLINE_ASSIST": [
        {"prompt_id": "P-SAFE-ONLINE-PACKAGE"},
        {"prompt_id": "P-SAFE-ONLINE-PACKAGE-CRITIC"},
        {"prompt_id": "P-PUBLIC-RESEARCH-PLAN"},
        {"type": "PUBLIC_SEARCH"},
        {"prompt_id": "P-PUBLIC-RESEARCH-SYNTHESIS"},
        {"prompt_id": "P-PUBLIC-RESEARCH-CRITIC"},
        {"prompt_id": "P-ONLINE-RESULT-IMPORT-CRITIC"},
    ],
    "WF-4_PROPOSAL_AUTHORING": [
        {"prompt_id": "P-REVISION-PLAN"},
        {"prompt_id": "P-REVISION-PLAN-CRITIC"},
        {"type": "WRITE_SECTIONS"},
        {"prompt_id": "P-INTEGRATION-CRITIC"},
    ],
    "WF-5_SECURITY_REVIEW_AND_EXPORT": [
        {"prompt_id": "P-FINAL-CONFIDENTIALITY-REVIEW"},
        {"type": "GATE", "gate_type": "FINAL_EXPORT_APPROVAL"},
    ],
}

GATE_ROLE = {
    "SCHEME_CONFIRMATION": "PROJECT_OWNER",
    "PROJECT_DEFINITION_CONFIRMATION": "PROJECT_OWNER",
    "PROJECT_GAP_RESOLUTION": "PROJECT_OWNER",
    "FACT_CONFIRMATION": "PROJECT_OWNER",
    "FACT_CONFLICT_RESOLUTION": "PROJECT_OWNER",
    "TEMPLATE_CONFIRMATION": "CONTENT_OPERATOR",
    "TECHNICAL_OR_METRIC_INFORMATION": "PROJECT_OWNER",
    "PLAN_CONFIRMATION": "PROJECT_OWNER",
    "CANDIDATE_REVIEW": "CONTENT_OPERATOR",
    "OUTBOUND_SECURITY_APPROVAL": "SECURITY_REVIEWER",
    "ONLINE_RESULT_IMPORT_APPROVAL": "SECURITY_REVIEWER",
    "FINAL_CONTENT_SECURITY_APPROVAL": "SECURITY_REVIEWER",
    "FINAL_EXPORT_APPROVAL": "EXPORT_APPROVER",
}

GATE_ACTIONS = {
    "OUTBOUND_SECURITY_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
    "ONLINE_RESULT_IMPORT_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
    "FINAL_CONTENT_SECURITY_APPROVAL": ["APROVE", "RETURN", "REJECT", "CANCEL"],
    "FINAL_EXPORT_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
}

CRITIC_PRODUCER = {
    "P-SECURITY-CLASSIFY-CRITIC": "P-SECURITY-CLASSIFY",
    "P-SAFE-ONLINE-PACKAGE-CRITIC": "P-SAFE-ONLINE-PACKAGE",
    "P-PUBLIC-RESEARCH-CRITIC": "P-PUBLIC-RESEARCH-SYNTHESIS",
    "P-SCHEME-CRITIC": "P-SCHEME-EXTRACT",
    "P-PROJECT-DEFINITION-CRITIC": "P-PROJECT-DEFINITION-EXTRACT",
    "P-FACT-CRITIC": "P-FACT-EXTRACT",
    "P-TEMPLATE-CRITIC": "P-TEMPLATE-EXTRACT",
    "P-REVISION-PLAN-CRITIC": "P-REVISION-PLAN",
    "P-WRITE-BLUEPRINT-CRITIC": "P-WRITE-BLUEPRINT",
    "P-WRITE-CRITIC": "P-WRITE-CONTENT",
}


