from __future__ import annotations

from typing import Any


WORKFLOWS: dict[str, list[dict[str, Any]]] = {
    "WF-1_PROJECT_INTAKE": [
        {"prompt_id": "P-SECURITY-CLASSIFY"},
        {"prompt_id": "P-SECURITY-CLASSIFY-CRITIC"},
        {"prompt_id": "P-SCHEME-EXTRACT"},
        {"prompt_id": "P-SCHEME-CRITIC"},
        {"prompt_id": "P-PROJECT-DEFINITION-EXTRACT"},
        {"prompt_id": "P-PROJECT-DEFINITION-CRITIC"},
        {"prompt_id": "P-FACT-EXTRACT"},
        {"prompt_id": "P-FACT-CRITIC"},
        {"prompt_id": "P-PROJECT-READINESS-CRITIC"},
    ],
    "WF-2_TEMPLATE_EXTRACTION": [
        {"prompt_id": "P-TEMPLATE-EXTRACT"},
        {"prompt_id": "P-TEMPLATE-CRITIC"},
    ],
    "WF-3_HYBRID_ONLINE_ASSIST": [
        {"prompt_id": "P-SAFE-ONLINE-PACKAGE"},
        {"prompt_id": "P-SAFE-ONLINE-PACKAGE-CRITIC"},
        {"prompt_id": "P-PUBLIC-RESEARCH-PLAN"},
        {"prompt_id": "P-PUBLIC-RESEARCH-PLAN-SCOPE-CRITIC"},
        {"type": "PUBLIC_SEARCH"},
        {"prompt_id": "P-PUBLIC-RESEARCH-SYNTHESIS"},
        {"prompt_id": "P-PUBLIC-RESEARCH-CRITIC"},
        {"prompt_id": "P-ONLINE-RESULT-IMPORT-CRITIC"},
    ],
    "WF-3B_TOPIC_BACKGROUND_RESEARCH": [
        {"prompt_id": "P-SAFE-ONLINE-PACKAGE"},
        {"prompt_id": "P-SAFE-ONLINE-PACKAGE-CRITIC"},
        {"prompt_id": "P-BACKGROUND-RESEARCH-PLAN"},
        {"prompt_id": "P-BACKGROUND-RESEARCH-PLAN-CRITIC"},
        {"type": "PUBLIC_SEARCH"},
        {"prompt_id": "P-BACKGROUND-RESEARCH-SYNTHESIS"},
        {"prompt_id": "P-BACKGROUND-RESEARCH-CRITIC"},
        {"prompt_id": "P-ONLINE-RESULT-IMPORT-CRITIC"},
    ],
    "WF-4_PROPOSAL_AUTHORING": [
        {"prompt_id": "P-ARGUMENT-ARCHITECTURE"},
        {"prompt_id": "P-ARGUMENT-ARCHITECTURE-CRITIC"},
        {"prompt_id": "P-PROJECT-READINESS-CRITIC"},
        {"prompt_id": "P-REVISION-PLAN"},
        {"prompt_id": "P-REVISION-PLAN-CRITIC"},
        {"type": "WRITE_SECTIONS"},
        {"prompt_id": "P-INTEGRATION-CRITIC"},
    ],
    "WF-5_SECURITY_REVIEW_AND_EXPORT": [
        {"prompt_id": "P-FINAL-CONFIDENTIALITY-REVIEW"},
        {"type": "GATE", "gate_type": "FINAL_EXPORT_APPROVAL"},
    ],
}

# WF-4 report branch (SURVEY_REPORT): frozen into the workflow state at start
# by document type; the proposal step list in WORKFLOWS stays untouched and
# this branch is not a separately startable workflow type.  Section writing
# and integration are appended to this branch in a later phase.
WF4_REPORT_BRANCH_STEPS: list[dict[str, Any]] = [
    {"prompt_id": "P-REPORT-OUTLINE"},
    {"prompt_id": "P-REPORT-OUTLINE-CRITIC"},
]

GATE_ROLE = {
    "SCHEME_CONFIRMATION": "PROJECT_OWNER",
    "PROJECT_DEFINITION_CONFIRMATION": "PROJECT_OWNER",
    "PROJECT_GAP_RESOLUTION": "PROJECT_OWNER",
    "FACT_CONFIRMATION": "PROJECT_OWNER",
    "FACT_CONFLICT_RESOLUTION": "PROJECT_OWNER",
    "TEMPLATE_CONFIRMATION": "CONTENT_OPERATOR",
    "TECHNICAL_OR_METRIC_INFORMATION": "PROJECT_OWNER",
    "ARGUMENT_ARCHITECTURE_CONFIRMATION": "PROJECT_OWNER",
    "PLAN_CONFIRMATION": "PROJECT_OWNER",
    "CANDIDATE_REVIEW": "CONTENT_OPERATOR",
    "OUTBOUND_SECURITY_APPROVAL": "SECURITY_REVIEWER",
    "PUBLIC_RESEARCH_NEED_INPUT": "PROJECT_OWNER",
    "PROJECT_MATERIAL_INPUT": "PROJECT_OWNER",
    "APPLICATION_GUIDE_INPUT": "PROJECT_OWNER",
    "REFERENCE_TEMPLATE_INPUT": "CONTENT_OPERATOR",
    "CURRENT_PROPOSAL_INPUT": "CONTENT_OPERATOR",
    "ONLINE_RESULT_IMPORT_APPROVAL": "SECURITY_REVIEWER",
    "FINAL_CONTENT_SECURITY_APPROVAL": "SECURITY_REVIEWER",
    "FINAL_EXPORT_APPROVAL": "EXPORT_APPROVER",
}

GATE_ACTIONS = {
    "OUTBOUND_SECURITY_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
    "PUBLIC_RESEARCH_NEED_INPUT": ["PROVIDE_INFORMATION", "RETURN", "CANCEL"],
    "PROJECT_MATERIAL_INPUT": ["PROVIDE_INFORMATION", "RETURN", "CANCEL"],
    "APPLICATION_GUIDE_INPUT": ["PROVIDE_INFORMATION", "RETURN", "CANCEL"],
    "REFERENCE_TEMPLATE_INPUT": ["PROVIDE_INFORMATION", "RETURN", "CANCEL"],
    "CURRENT_PROPOSAL_INPUT": ["PROVIDE_INFORMATION", "RETURN", "CANCEL"],
    "ONLINE_RESULT_IMPORT_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
    "FINAL_CONTENT_SECURITY_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
    "FINAL_EXPORT_APPROVAL": ["APPROVE", "RETURN", "REJECT", "CANCEL"],
}

CRITIC_PRODUCER = {
    "P-SECURITY-CLASSIFY-CRITIC": "P-SECURITY-CLASSIFY",
    "P-SAFE-ONLINE-PACKAGE-CRITIC": "P-SAFE-ONLINE-PACKAGE",
    "P-PUBLIC-RESEARCH-PLAN-SCOPE-CRITIC": "P-PUBLIC-RESEARCH-PLAN",
    "P-PUBLIC-RESEARCH-CRITIC": "P-PUBLIC-RESEARCH-SYNTHESIS",
    "P-BACKGROUND-RESEARCH-PLAN-CRITIC": "P-BACKGROUND-RESEARCH-PLAN",
    "P-BACKGROUND-RESEARCH-CRITIC": "P-BACKGROUND-RESEARCH-SYNTHESIS",
    "P-SCHEME-CRITIC": "P-SCHEME-EXTRACT",
    "P-PROJECT-DEFINITION-CRITIC": "P-PROJECT-DEFINITION-EXTRACT",
    "P-FACT-CRITIC": "P-FACT-EXTRACT",
    "P-TEMPLATE-CRITIC": "P-TEMPLATE-EXTRACT",
    "P-ARGUMENT-ARCHITECTURE-CRITIC": "P-ARGUMENT-ARCHITECTURE",
    "P-REVISION-PLAN-CRITIC": "P-REVISION-PLAN",
    "P-WRITE-BLUEPRINT-CRITIC": "P-WRITE-BLUEPRINT",
    "P-WRITE-CRITIC": "P-WRITE-CONTENT",
    "P-EXPRESSION-CRITIC": "P-EXPRESSION-POLISH",
    "P-REPORT-OUTLINE-CRITIC": "P-REPORT-OUTLINE",
}


